import torch
import torch.nn as nn
from typing import Optional, Tuple, Dict, Union, Any


class LabelEncoder(nn.Module):
    """
    Class-Agnostic Label Encoder supporting Dictionary Targets and PyTorch vmap.
    
    If targets are passed as Dictionaries containing a 'labels' key:
    - Automatically encodes the 'labels' tensor across Support and Query sets consistently.
    - Preserves all other key-value pairs (e.g., domain IDs, regression targets) untouched.
    """

    def __init__(
        self, 
        num_classes: int, 
        max_n_way: Optional[int] = None, 
        shuffle: bool = True
    ):
        """
        Initializes LabelEncoder with spectrum buffers and permutation options.

        Args:
            num_classes (int): Total number of unique base classes across dataset.
            max_n_way (Optional[int]): Maximum number of target slots/ways per task.
            shuffle (bool): If True, randomly permutes task class integer mappings.
        """
        # Initialize PyTorch parent module
        super().__init__()
        # Store dataset class count
        self.num_classes = num_classes
        # Store upper limit for task ways
        self.max_n_way = max_n_way
        # Store shuffling configuration boolean
        self.shuffle = shuffle
        
        # Spectrum buffer: [0, 1, ..., num_classes - 1]
        self.register_buffer("class_spectrum", torch.arange(num_classes), persistent=False)

    def generate_mapping(self, y_support: torch.Tensor) -> torch.Tensor:
        """
        Generates mapping table strictly based on present classes in support labels.

        Args:
            y_support (torch.Tensor): Raw support label tensor.

        Returns:
            torch.Tensor: Mapping table array linking dataset classes to relative task indices.
        """
        # Retrieve active execution device from support label tensor
        device = y_support.device
        # Align class spectrum buffer with current tensor device
        class_spectrum = self.class_spectrum.to(device)

        # Construct one-hot tensor over dataset spectrum
        one_hot_supp = (y_support.unsqueeze(-1) == class_spectrum).to(torch.float32)
        # Flatten sample dimensions for class counting
        flat_one_hot = one_hot_supp.reshape(-1, self.num_classes)
        # Determine presence of each class in support set
        class_presence = (flat_one_hot.sum(dim=0) > 0).to(torch.int64)

        # Calculate zero-indexed rank for present classes
        class_ranks = torch.cumsum(class_presence, dim=0) - 1

        # Process random class slot permutation if shuffle is enabled
        if self.shuffle:
            if self.max_n_way is not None:
                # Generate random scores for slot assignment
                slot_scores = torch.rand(self.max_n_way, device=y_support.device, dtype=torch.float32)
                # Sort indices based on random scores
                available_slots = torch.argsort(slot_scores)
                # Map class ranks to available random slots
                slots_mapped = available_slots[class_ranks.clamp(min=0)]
            else:
                # Use standard sequential ranks if no max_n_way bound exists
                slots_mapped = class_ranks

            # Generate random permutation scores for class spectrum
            shuffle_scores = torch.rand_like(class_spectrum, dtype=torch.float32)
            # Obtain random permutation indices
            perm_indices = torch.argsort(shuffle_scores)
            
            # Apply permutation mapping to mapped slots
            shuffled_slots = slots_mapped[perm_indices]
            # Calculate inverse permutation indices
            inv_perm = torch.argsort(perm_indices)
            # Reconstruct final randomized mapping table
            mapping_table = shuffled_slots[inv_perm]
        else:
            # Use deterministic cumulative ranks when shuffle is False
            mapping_table = class_ranks

        # Mask out absent classes with -1 index
        mapping_table = torch.where(
            class_presence > 0, 
            mapping_table, 
            torch.tensor(-1, device=y_support.device, dtype=torch.int64)
        )

        # Return pre-computed class mapping lookup table
        return mapping_table

    def apply_mapping(self, targets: torch.Tensor, mapping_table: torch.Tensor) -> torch.Tensor:
        """
        Applies pre-computed mapping table to target labels tensor.

        Args:
            targets (torch.Tensor): Raw target labels tensor.
            mapping_table (torch.Tensor): Mapping table generated by generate_mapping.

        Returns:
            torch.Tensor: Encoded target labels tensor mapped to task slot range.
        """
        # Retrieve target tensor device
        device = targets.device
        # Align class spectrum buffer device
        class_spectrum = self.class_spectrum.to(device)

        # Convert targets to one-hot format over dataset spectrum
        one_hot = (targets.unsqueeze(-1) == class_spectrum).to(torch.float32)
        # Apply matrix multiplication to map one-hot vectors to re-indexed integers
        encoded_targets = torch.matmul(one_hot, mapping_table.to(one_hot.dtype)).to(torch.int64)

        # Return re-mapped label tensor
        return encoded_targets

    def _encode_tensor_pair(
        self, 
        y_supp_tensor: torch.Tensor, 
        y_query_tensor: torch.Tensor
    ) -> Tuple[torch.Tensor, torch.Tensor]:
        """
        Core encoding routine for support and query label tensors.

        Args:
            y_supp_tensor (torch.Tensor): Raw support set labels tensor.
            y_query_tensor (torch.Tensor): Raw query set labels tensor.

        Returns:
            Tuple[torch.Tensor, torch.Tensor]: Encoded support and query set label tensors.
        """
        # Compute joint class mapping table based strictly on support set classes
        mapping_table = self.generate_mapping(y_supp_tensor)
        # Transform support labels using calculated mapping
        enc_supp = self.apply_mapping(y_supp_tensor, mapping_table)
        # Transform query labels using identical support mapping
        enc_query = self.apply_mapping(y_query_tensor, mapping_table)
        # Return encoded tensor pair
        return enc_supp, enc_query

    def forward(
        self, 
        y_support: Union[torch.Tensor, Dict[str, Any]], 
        y_query: Union[torch.Tensor, Dict[str, Any]]
    ) -> Tuple[Union[torch.Tensor, Dict[str, Any]], Union[torch.Tensor, Dict[str, Any]]]:
        """
        Encodes Support and Query targets, automatically handling Dictionary target structures.

        Args:
            y_support (Union[torch.Tensor, Dict[str, Any]]): Support set target tensor or target dict.
            y_query (Union[torch.Tensor, Dict[str, Any]]): Query set target tensor or target dict.

        Returns:
            Tuple[Union[torch.Tensor, Dict[str, Any]], Union[torch.Tensor, Dict[str, Any]]]: Encoded targets.
        """

        # Verify input targets are raw PyTorch tensors and process pair
        if isinstance(y_support, torch.Tensor) and isinstance(y_query, torch.Tensor):
            return self._encode_tensor_pair(y_support, y_query)

        else:
            # Raise exception if input format is unsupported
            raise TypeError("❌ Invalid Target Type: Expected torch.Tensor or Dict containing 'labels' key.")